# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: interface.proto
# Protobuf Python Version: 5.26.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0finterface.proto\x12\tinterface\"d\n\x08Waypoint\x12\x1a\n\rposition_long\x18\x01 \x01(\x01H\x00\x88\x01\x01\x12\x19\n\x0cposition_lat\x18\x02 \x01(\x01H\x01\x88\x01\x01\x42\x10\n\x0e_position_longB\x0f\n\r_position_lat\"g\n\x08Obstacle\x12*\n\x08location\x18\x01 \x01(\x0b\x32\x13.interface.WaypointH\x00\x88\x01\x01\x12\x15\n\x08radius_m\x18\x02 \x01(\x01H\x01\x88\x01\x01\x42\x0b\n\t_locationB\x0b\n\t_radius_m\"\xcf\x01\n\x07ToDrone\x12\x31\n\ngen_status\x18\x01 \x01(\x0e\x32\x18.interface.GeneralStatusH\x00\x88\x01\x01\x12.\n\x0cnew_waypoint\x18\x02 \x01(\x0b\x32\x13.interface.WaypointH\x01\x88\x01\x01\x12/\n\rtare_position\x18\x03 \x01(\x0b\x32\x13.interface.WaypointH\x02\x88\x01\x01\x42\r\n\x0b_gen_statusB\x0f\n\r_new_waypointB\x10\n\x0e_tare_position\"\xd5\x02\n\x08ToSensor\x12\x31\n\ngen_status\x18\x01 \x01(\x0e\x32\x18.interface.GeneralStatusH\x00\x88\x01\x01\x12\x31\n\x0c\x64rone_status\x18\x02 \x01(\x0e\x32\x16.interface.DroneStatusH\x01\x88\x01\x01\x12\x32\n\x10\x63urrent_position\x18\x03 \x01(\x0b\x32\x13.interface.WaypointH\x02\x88\x01\x01\x12/\n\rnext_position\x18\x04 \x01(\x0b\x32\x13.interface.WaypointH\x03\x88\x01\x01\x12*\n\x08obstacle\x18\x05 \x01(\x0b\x32\x13.interface.ObstacleH\x04\x88\x01\x01\x42\r\n\x0b_gen_statusB\x0f\n\r_drone_statusB\x13\n\x11_current_positionB\x10\n\x0e_next_positionB\x0b\n\t_obstacle*0\n\rGeneralStatus\x12\r\n\tSTATUS_OK\x10\x00\x12\x10\n\x0cSTATUS_FAULT\x10\x01*h\n\x0b\x44roneStatus\x12\x19\n\x15\x44RONE_STATUS_GROUNDED\x10\x00\x12\x19\n\x15\x44RONE_STATUS_HOVERING\x10\x01\x12#\n\x1f\x44RONE_STATUS_MOVING_TO_WAYPOINT\x10\x02\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'interface_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GENERALSTATUS']._serialized_start=791
  _globals['_GENERALSTATUS']._serialized_end=839
  _globals['_DRONESTATUS']._serialized_start=841
  _globals['_DRONESTATUS']._serialized_end=945
  _globals['_WAYPOINT']._serialized_start=30
  _globals['_WAYPOINT']._serialized_end=130
  _globals['_OBSTACLE']._serialized_start=132
  _globals['_OBSTACLE']._serialized_end=235
  _globals['_TODRONE']._serialized_start=238
  _globals['_TODRONE']._serialized_end=445
  _globals['_TOSENSOR']._serialized_start=448
  _globals['_TOSENSOR']._serialized_end=789
# @@protoc_insertion_point(module_scope)
